#!/bin/bash
# deploy-history.sh — Read win-history.json, regenerate backfillHistory.js, build & deploy.
set -e
cd "$(dirname "$0")/.."

HISTORY_FILE="scripts/score-history.json"
BACKFILL_FILE="src/data/backfillHistory.js"

if [ ! -f "$HISTORY_FILE" ]; then
  echo "Error: $HISTORY_FILE not found. Run snapshot.mjs first."
  exit 1
fi

SNAPSHOT_COUNT=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$HISTORY_FILE','utf-8')).length)")
echo "Found $SNAPSHOT_COUNT snapshots in $HISTORY_FILE"

echo "Generating $BACKFILL_FILE..."
node -e "
const fs = require('fs');
const history = JSON.parse(fs.readFileSync('$HISTORY_FILE', 'utf-8'));
const lines = history.map(s => '  ' + JSON.stringify(s));
const out = '// Auto-generated by deploy-history.sh on ' + new Date().toISOString() + '\n'
  + '// ' + history.length + ' snapshots\n'
  + 'export const BACKFILL_HISTORY = [\n'
  + lines.join(',\n') + ',\n'
  + '];\n';
fs.writeFileSync('$BACKFILL_FILE', out);
"
echo "Wrote $BACKFILL_FILE"

echo "Building..."
npm run build

echo "Deploying to Vercel..."
npx vercel --prod --yes 2>&1 | tee /tmp/vercel-deploy.log

DEPLOY_URL=$(grep -oE 'https://[^ ]+\.vercel\.app' /tmp/vercel-deploy.log | tail -1)
echo "Deploy URL: $DEPLOY_URL"

if [ -n "$DEPLOY_URL" ]; then
  echo "Setting alias to masters-app-rosy.vercel.app..."
  npx vercel alias "$DEPLOY_URL" masters-app-rosy.vercel.app 2>&1
fi

echo "Done! Live at: https://masters-app-rosy.vercel.app"
