#!/bin/bash
# deploy-history.sh — Run snapshot, regenerate backfillHistory.js, commit & push.
# Run manually each evening at ~8pm CST to hardcode the day's scores.
# Vercel auto-deploys on push to main.
set -e
cd "$(dirname "$0")/.."

HISTORY_FILE="scripts/score-history.json"
BACKFILL_FILE="src/data/backfillHistory.js"

if [ ! -f "$HISTORY_FILE" ]; then
  echo "Error: $HISTORY_FILE not found. Run snapshot.mjs first."
  exit 1
fi

SNAPSHOT_COUNT=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$HISTORY_FILE','utf-8')).length)")
echo "Found $SNAPSHOT_COUNT snapshots in $HISTORY_FILE"

echo "Generating $BACKFILL_FILE..."
node -e "
const fs = require('fs');
const history = JSON.parse(fs.readFileSync('$HISTORY_FILE', 'utf-8'));
const lines = history.map(s => '  ' + JSON.stringify(s));
const out = '// Auto-generated by deploy-history.sh on ' + new Date().toISOString() + '\n'
  + '// ' + history.length + ' snapshots\n'
  + 'export const BACKFILL_HISTORY = [\n'
  + lines.join(',\n') + ',\n'
  + '];\n';
fs.writeFileSync('$BACKFILL_FILE', out);
"
echo "Wrote $BACKFILL_FILE"

echo "Committing and pushing (Vercel auto-deploys on push)..."
git add scripts/score-history.json src/data/backfillHistory.js
git diff --cached --quiet && echo "No changes to commit" && exit 0
git commit -m "chore: end-of-day score snapshot $(date -u +%Y-%m-%dT%H:%M:%SZ)"
git push origin main

echo "Done! Vercel will auto-deploy."
